/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "powerfox2 adapter settings": {
    "en": "Adapter settings for powerfox",
    "de": "Adaptereinstellungen für powerfox",
    "ru": "Настройки адаптера для powerfox",
    "pt": "Configurações do adaptador para powerfox",
    "nl": "Adapterinstellingen voor powerfox",
    "fr": "Paramètres d'adaptateur pour powerfox",
    "it": "Impostazioni dell'adattatore per powerfox",
    "es": "Ajustes del adaptador para powerfox",
    "pl": "Ustawienia adaptera dla powerfox",
    "zh-cn": "powerfox的适配器设置"
  },
  "email": {
    "en": "email",
    "de": "E-Mail",
    "ru": "Эл. адрес",
    "pt": "o email",
    "nl": "e-mail",
    "fr": "email",
    "it": "e-mail",
    "es": "correo electrónico",
    "pl": "e-mail",
    "zh-cn": "电子邮件"
  },
  "password": {
    "en": "password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "senha",
    "nl": "wachtwoord",
    "fr": "mot de passe",
    "it": "parola d'ordine",
    "es": "contraseña",
    "pl": "hasło",
    "zh-cn": "密码"
  },
  "day interval": {
    "en": "Day interval (min.)",
    "de": "Tagesintervall (Min.)",
    "ru": "Дневной интервал (мин.)",
    "pt": "Intervalo diurno (min.)",
    "nl": "Daginterval (min.)",
    "fr": "Intervalle de jour (min.)",
    "it": "Intervallo diurno (min.)",
    "es": "Intervalo diurno (min.)",
    "pl": "Interwał dzienny (min.)",
    "zh-cn": "白天间隔（分钟）"
  },
  "day interval hint": {
    "en": "Query interval between night end and night start (1–60)",
    "de": "Abfrageintervall zwischen Nachtende und Nachtstart (1–60)",
    "ru": "Интервал опроса между концом и началом ночи (1–60)",
    "pt": "Intervalo entre fim e início da noite (1–60)",
    "nl": "Opvraaginterval tussen nacht einde en start (1–60)",
    "fr": "Intervalle entre fin et début de nuit (1–60)",
    "it": "Intervallo tra fine e inizio notte (1–60)",
    "es": "Intervalo entre fin e inicio de noche (1–60)",
    "pl": "Interwał między końcem a początkiem nocy (1–60)",
    "zh-cn": "夜间结束到夜间开始之间的查询间隔（1–60）"
  },
  "night interval": {
    "en": "Night interval (min.)",
    "de": "Nachtintervall (Min.)",
    "ru": "Ночной интервал (мин.)",
    "pt": "Intervalo noturno (min.)",
    "nl": "Nachtinterval (min.)",
    "fr": "Intervalle de nuit (min.)",
    "it": "Intervallo notturno (min.)",
    "es": "Intervalo nocturno (min.)",
    "pl": "Interwał nocny (min.)",
    "zh-cn": "夜间间隔（分钟）"
  },
  "night interval hint": {
    "en": "Query interval between night start and night end (1–60)",
    "de": "Abfrageintervall zwischen Nachtstart und Nachtende (1–60)",
    "ru": "Интервал опроса между началом и концом ночи (1–60)",
    "pt": "Intervalo entre início e fim da noite (1–60)",
    "nl": "Opvraaginterval tussen nacht start en einde (1–60)",
    "fr": "Intervalle entre début et fin de nuit (1–60)",
    "it": "Intervallo tra inizio e fine notte (1–60)",
    "es": "Intervalo entre inicio y fin de noche (1–60)",
    "pl": "Interwał między początkiem a końcem nocy (1–60)",
    "zh-cn": "夜间开始到夜间结束之间的查询间隔（1–60）"
  },
  "night start": {
    "en": "Night start (hour)",
    "de": "Nachtstart (Uhr)",
    "ru": "Начало ночи (час)",
    "pt": "Início da noite (hora)",
    "nl": "Nacht start (uur)",
    "fr": "Début de nuit (heure)",
    "it": "Inizio notte (ora)",
    "es": "Inicio de noche (hora)",
    "pl": "Początek nocy (godz.)",
    "zh-cn": "夜间开始（小时）"
  },
  "night start hint": {
    "en": "Night interval starts at this hour (0–23, e.g. 22 = 10 PM)",
    "de": "Nachtintervall startet ab dieser Uhrzeit (0–23, z.B. 22 = 22:00 Uhr)",
    "ru": "Ночной интервал начинается с этого часа (0–23)",
    "pt": "Intervalo noturno começa nesta hora (0–23)",
    "nl": "Nachtinterval begint op dit uur (0–23)",
    "fr": "L'intervalle de nuit commence à cette heure (0–23)",
    "it": "L'intervallo notturno inizia a quest'ora (0–23)",
    "es": "El intervalo nocturno comienza a esta hora (0–23)",
    "pl": "Interwał nocny zaczyna się o tej godzinie (0–23)",
    "zh-cn": "夜间间隔从该小时开始（0–23）"
  },
  "night end": {
    "en": "Night end (hour)",
    "de": "Nachtende (Uhr)",
    "ru": "Конец ночи (час)",
    "pt": "Fim da noite (hora)",
    "nl": "Nacht einde (uur)",
    "fr": "Fin de nuit (heure)",
    "it": "Fine notte (ora)",
    "es": "Fin de noche (hora)",
    "pl": "Koniec nocy (godz.)",
    "zh-cn": "夜间结束（小时）"
  },
  "night end hint": {
    "en": "Day interval resumes at this hour (0–23, e.g. 6 = 6 AM)",
    "de": "Tagesintervall gilt wieder ab dieser Uhrzeit (0–23, z.B. 6 = 06:00 Uhr)",
    "ru": "Дневной интервал возобновляется с этого часа (0–23)",
    "pt": "Intervalo diurno retoma nesta hora (0–23)",
    "nl": "Daginterval hervat op dit uur (0–23)",
    "fr": "L'intervalle de jour reprend à cette heure (0–23)",
    "it": "L'intervallo diurno riprende a quest'ora (0–23)",
    "es": "El intervalo diurno reanuda a esta hora (0–23)",
    "pl": "Interwał dzienny wznawia się o tej godzinie (0–23)",
    "zh-cn": "白天间隔从该小时恢复（0–23）"
  },
  "device list": {
    "en": "device list",
    "de": "Geräteliste",
    "ru": "список устройств",
    "pt": "lista de dispositivos",
    "nl": "lijst met apparaten",
    "fr": "liste des périphériques",
    "it": "elenco dei dispositivi",
    "es": "lista de dispositivos",
    "pl": "Lista urządzeń",
    "zh-cn": "设备清单"
  },
  "update device list": {
    "en": "update device list",
    "de": "Geräteliste aktualisieren",
    "ru": "обновить список устройств",
    "pt": "atualizar lista de dispositivos",
    "nl": "update apparaatlijst",
    "fr": "mettre à jour la liste des appareils",
    "it": "aggiorna l'elenco dei dispositivi",
    "es": "actualizar lista de dispositivos",
    "pl": "zaktualizuj listę urządzeń",
    "zh-cn": "更新设备列表"
  },
  "wrong credentials": {
    "en": "wrong credentials",
    "de": "falsche Anmeldeinformationen",
    "ru": "неправильные учетные данные",
    "pt": "credenciais erradas",
    "nl": "verkeerde inloggegevens",
    "fr": "fausses informations d'identification",
    "it": "credenziali sbagliate",
    "es": "Credenciales incorrectas",
    "pl": "błędne dane uwierzytelniające",
    "zh-cn": "凭证错误"
  },
  "error occurred": {
    "en": "error occurred",
    "de": "Ein Fehler ist aufgetreten",
    "ru": "произошла ошибка",
    "pt": "ocorreu um erro",
    "nl": "fout opgetreden",
    "fr": "erreur est survenue",
    "it": "Errore",
    "es": "Se produjo un error",
    "pl": "Wystąpił błąd",
    "zh-cn": "错误发生"
  },
  "Devices": {
    "en": "Devices",
    "de": "Geräte",
    "ru": "Устройства",
    "pt": "Dispositivos",
    "nl": "Apparaten",
    "fr": "Dispositifs",
    "it": "dispositivi",
    "es": "Dispositivos",
    "pl": "Urządzenia",
    "zh-cn": "设备"
  },
  "Options": {
    "en": "Options",
    "de": "Optionen",
    "ru": "Параметры",
    "pt": "Opções",
    "nl": "Opties",
    "fr": "Options",
    "it": "Opzioni",
    "es": "Opciones",
    "pl": "Opcje",
    "zh-cn": "选件"
  },
  "device name": {
    "en": "device name",
    "de": "Gerätename",
    "ru": "имя устройства",
    "pt": "nome do dispositivo",
    "nl": "toestelnaam",
    "fr": "nom de l'appareil",
    "it": "nome del dispositivo",
    "es": "nombre del dispositivo",
    "pl": "Nazwa urządzenia",
    "zh-cn": "设备名称"
  },
  "associated since": {
    "en": "associated since",
    "de": "verbunden seit",
    "ru": "связаны с",
    "pt": "associado desde",
    "nl": "geassocieerd sinds",
    "fr": "associé depuis",
    "it": "associato da allora",
    "es": "asociado desde",
    "pl": "związane od",
    "zh-cn": "关联自"
  },
  "active": {
    "en": "active",
    "de": "aktiv",
    "ru": "активный",
    "pt": "ativo",
    "nl": "actief",
    "fr": "actif",
    "it": "attivo",
    "es": "activo",
    "pl": "aktywny",
    "zh-cn": "活性"
  },
  "meter type": {
    "en": "meter type",
    "de": "Zählertyp",
    "ru": "тип счётчика",
    "pt": "tipo de medidor",
    "nl": "metertype",
    "fr": "type de compteur",
    "it": "tipo di contatore",
    "es": "tipo de contador",
    "pl": "typ licznika",
    "zh-cn": "计量表类型"
  },
  "division no type": {
    "en": "no type",
    "de": "Kein Typ",
    "ru": "нет типа",
    "pt": "sem tipo",
    "nl": "geen type",
    "fr": "aucun type",
    "it": "nessun tipo",
    "es": "sin tipo",
    "pl": "brak typu",
    "zh-cn": "无类型"
  },
  "division electricity": {
    "en": "electricity meter",
    "de": "Stromzähler",
    "ru": "счётчик электроэнергии",
    "pt": "medidor de eletricidade",
    "nl": "elektriciteitsmeter",
    "fr": "compteur d'électricité",
    "it": "contatore elettrico",
    "es": "contador de electricidad",
    "pl": "licznik energii elektrycznej",
    "zh-cn": "电表"
  },
  "division cold water": {
    "en": "cold water meter",
    "de": "Kaltwasserzähler",
    "ru": "счётчик холодной воды",
    "pt": "medidor de água fria",
    "nl": "koudwatermeter",
    "fr": "compteur d'eau froide",
    "it": "contatore acqua fredda",
    "es": "contador de agua fría",
    "pl": "licznik zimnej wody",
    "zh-cn": "冷水表"
  },
  "division hot water": {
    "en": "hot water meter",
    "de": "Warmwasserzähler",
    "ru": "счётчик горячей воды",
    "pt": "medidor de água quente",
    "nl": "warmwatermeter",
    "fr": "compteur d'eau chaude",
    "it": "contatore acqua calda",
    "es": "contador de agua caliente",
    "pl": "licznik ciepłej wody",
    "zh-cn": "热水表"
  },
  "division heat": {
    "en": "heat meter",
    "de": "Wärmezähler",
    "ru": "счётчик тепла",
    "pt": "medidor de calor",
    "nl": "warmtemeter",
    "fr": "compteur de chaleur",
    "it": "contatore di calore",
    "es": "contador de calor",
    "pl": "licznik ciepła",
    "zh-cn": "热量表"
  },
  "division gas": {
    "en": "gas meter",
    "de": "Gaszähler",
    "ru": "газовый счётчик",
    "pt": "medidor de gás",
    "nl": "gasmeter",
    "fr": "compteur de gaz",
    "it": "contatore del gas",
    "es": "contador de gas",
    "pl": "licznik gazu",
    "zh-cn": "燃气表"
  },
  "division cold and hot water": {
    "en": "cold and hot water meter",
    "de": "Kalt- und Warmwasserzähler",
    "ru": "счётчик холодной и горячей воды",
    "pt": "medidor de água fria e quente",
    "nl": "koud- en warmwatermeter",
    "fr": "compteur eau froide et chaude",
    "it": "contatore acqua fredda e calda",
    "es": "contador de agua fría y caliente",
    "pl": "licznik zimnej i ciepłej wody",
    "zh-cn": "冷热水表"
  }
};
