/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "powerfox2 adapter settings": {
    "en": "Adapter settings for powerfox",
    "de": "Adaptereinstellungen für powerfox",
    "ru": "Настройки адаптера для powerfox",
    "pt": "Configurações do adaptador para powerfox",
    "nl": "Adapterinstellingen voor powerfox",
    "fr": "Paramètres d'adaptateur pour powerfox",
    "it": "Impostazioni dell'adattatore per powerfox",
    "es": "Ajustes del adaptador para powerfox",
    "pl": "Ustawienia adaptera dla powerfox",
    "zh-cn": "powerfox的适配器设置"
  },
  "email": {
    "en": "email",
    "de": "E-Mail",
    "ru": "Эл. адрес",
    "pt": "o email",
    "nl": "e-mail",
    "fr": "email",
    "it": "e-mail",
    "es": "correo electrónico",
    "pl": "e-mail",
    "zh-cn": "电子邮件"
  },
  "password": {
    "en": "password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "senha",
    "nl": "wachtwoord",
    "fr": "mot de passe",
    "it": "parola d'ordine",
    "es": "contraseña",
    "pl": "hasło",
    "zh-cn": "密码"
  },
  "device list": {
    "en": "device list",
    "de": "Geräteliste",
    "ru": "список устройств",
    "pt": "lista de dispositivos",
    "nl": "lijst met apparaten",
    "fr": "liste des périphériques",
    "it": "elenco dei dispositivi",
    "es": "lista de dispositivos",
    "pl": "Lista urządzeń",
    "zh-cn": "设备清单"
  },
  "update device list": {
    "en": "update device list",
    "de": "Geräteliste aktualisieren",
    "ru": "обновить список устройств",
    "pt": "atualizar lista de dispositivos",
    "nl": "update apparaatlijst",
    "fr": "mettre à jour la liste des appareils",
    "it": "aggiorna l'elenco dei dispositivi",
    "es": "actualizar lista de dispositivos",
    "pl": "zaktualizuj listę urządzeń",
    "zh-cn": "更新设备列表"
  },
  "wrong credentials": {
    "en": "wrong credentials",
    "de": "falsche Anmeldeinformationen",
    "ru": "неправильные учетные данные",
    "pt": "credenciais erradas",
    "nl": "verkeerde inloggegevens",
    "fr": "fausses informations d'identification",
    "it": "credenziali sbagliate",
    "es": "Credenciales incorrectas",
    "pl": "błędne dane uwierzytelniające",
    "zh-cn": "凭证错误"
  },
  "error occurred": {
    "en": "error occurred",
    "de": "Ein Fehler ist aufgetreten",
    "ru": "произошла ошибка",
    "pt": "ocorreu um erro",
    "nl": "fout opgetreden",
    "fr": "erreur est survenue",
    "it": "Errore",
    "es": "Se produjo un error",
    "pl": "Wystąpił błąd",
    "zh-cn": "错误发生"
  },
  "Devices": {
    "en": "Devices",
    "de": "Geräte",
    "ru": "Устройства",
    "pt": "Dispositivos",
    "nl": "Apparaten",
    "fr": "Dispositifs",
    "it": "dispositivi",
    "es": "Dispositivos",
    "pl": "Urządzenia",
    "zh-cn": "设备"
  },
  "Options": {
    "en": "Options",
    "de": "Optionen",
    "ru": "Параметры",
    "pt": "Opções",
    "nl": "Opties",
    "fr": "Options",
    "it": "Opzioni",
    "es": "Opciones",
    "pl": "Opcje",
    "zh-cn": "选件"
  },
  "device name": {
    "en": "device name",
    "de": "Gerätename",
    "ru": "имя устройства",
    "pt": "nome do dispositivo",
    "nl": "toestelnaam",
    "fr": "nom de l'appareil",
    "it": "nome del dispositivo",
    "es": "nombre del dispositivo",
    "pl": "Nazwa urządzenia",
    "zh-cn": "设备名称"
  },
  "associated since": {
    "en": "associated since",
    "de": "verbunden seit",
    "ru": "связаны с",
    "pt": "associado desde",
    "nl": "geassocieerd sinds",
    "fr": "associé depuis",
    "it": "associato da allora",
    "es": "asociado desde",
    "pl": "związane od",
    "zh-cn": "关联自"
  },
  "active": {
    "en": "active",
    "de": "aktiv",
    "ru": "активный",
    "pt": "ativo",
    "nl": "actief",
    "fr": "actif",
    "it": "attivo",
    "es": "activo",
    "pl": "aktywny",
    "zh-cn": "活性"
  },
  "meter type": {
    "en": "meter type",
    "de": "Zählertyp",
    "ru": "тип счётчика",
    "pt": "tipo de medidor",
    "nl": "metertype",
    "fr": "type de compteur",
    "it": "tipo di contatore",
    "es": "tipo de contador",
    "pl": "typ licznika",
    "zh-cn": "计量表类型"
  },
  "division no type": {
    "en": "no type",
    "de": "Kein Typ",
    "ru": "нет типа",
    "pt": "sem tipo",
    "nl": "geen type",
    "fr": "aucun type",
    "it": "nessun tipo",
    "es": "sin tipo",
    "pl": "brak typu",
    "zh-cn": "无类型"
  },
  "division electricity": {
    "en": "electricity meter",
    "de": "Stromzähler",
    "ru": "счётчик электроэнергии",
    "pt": "medidor de eletricidade",
    "nl": "elektriciteitsmeter",
    "fr": "compteur d'électricité",
    "it": "contatore elettrico",
    "es": "contador de electricidad",
    "pl": "licznik energii elektrycznej",
    "zh-cn": "电表"
  },
  "division cold water": {
    "en": "cold water meter",
    "de": "Kaltwasserzähler",
    "ru": "счётчик холодной воды",
    "pt": "medidor de água fria",
    "nl": "koudwatermeter",
    "fr": "compteur d'eau froide",
    "it": "contatore acqua fredda",
    "es": "contador de agua fría",
    "pl": "licznik zimnej wody",
    "zh-cn": "冷水表"
  },
  "division hot water": {
    "en": "hot water meter",
    "de": "Warmwasserzähler",
    "ru": "счётчик горячей воды",
    "pt": "medidor de água quente",
    "nl": "warmwatermeter",
    "fr": "compteur d'eau chaude",
    "it": "contatore acqua calda",
    "es": "contador de agua caliente",
    "pl": "licznik ciepłej wody",
    "zh-cn": "热水表"
  },
  "division heat": {
    "en": "heat meter",
    "de": "Wärmezähler",
    "ru": "счётчик тепла",
    "pt": "medidor de calor",
    "nl": "warmtemeter",
    "fr": "compteur de chaleur",
    "it": "contatore di calore",
    "es": "contador de calor",
    "pl": "licznik ciepła",
    "zh-cn": "热量表"
  },
  "division gas": {
    "en": "gas meter",
    "de": "Gaszähler",
    "ru": "газовый счётчик",
    "pt": "medidor de gás",
    "nl": "gasmeter",
    "fr": "compteur de gaz",
    "it": "contatore del gas",
    "es": "contador de gas",
    "pl": "licznik gazu",
    "zh-cn": "燃气表"
  },
  "division cold and hot water": {
    "en": "cold and hot water meter",
    "de": "Kalt- und Warmwasserzähler",
    "ru": "счётчик холодной и горячей воды",
    "pt": "medidor de água fria e quente",
    "nl": "koud- en warmwatermeter",
    "fr": "compteur eau froide et chaude",
    "it": "contatore acqua fredda e calda",
    "es": "contador de agua fría y caliente",
    "pl": "licznik zimnej i ciepłej wody",
    "zh-cn": "冷热水表"
  }
};
